### PR TITLE
#22 #20 Introduces compatibility with Strapi v4 + Permalinks + Collect assets filter

### PR DESCRIPTION
**Pull request by bluszcz**
Keeps basic functionality of permalinks
Adds new filter *asset_url*

Described in README examples requires following collection to be setup up and with permissions findone and find for Public:

image

With provided PRI am able to create following site. Permalinks are working, at least  *:id*. 

I really like new filter *asset_url* which collects locally remote assets.

Everything needs bit more testing. Also, this is my first Ruby code ever, but it feels similar to Python, at least a bit. If you like PR, I could maintain the project. Cheers.

image
image

### CODE REVIEW

**Comment by oDinZu** [comment]
Hi :wave:  The plugin works with PR #21. You can see more chat details on discord via frontend-other.

Great work on the filter.

I would like to add this to #21. I know #21 works for certain; Daedalus and I  made the smallest changes possible.

**Comment by oDinZu** [comment]
Also, for populating all data: all I do is add it to the URL: https://api.example.com/api/posts?populate=* via my web browser.

**Comment by bluszcz** [comment]
> Hi 👋 The plugin works with PR #21. You can see more chat details on discord via frontend-other.
> 
> Great work on the filter.
> 
> I would like to add this to #21. I know #21 works for certain; Daedalus and I made the smallest changes possible.

Hello @csharpee :), thank you for the feedback. Please feel free to reuse whatever you feel to :) I also added authentication in the another PR. [edit] <- actually made the latest didn't have too much sense, since it kind of duplicates changes here...

> Also, for populating all data: all I do is add it to the URL: https://api.example.com/api/posts?populate=* via my web browser.

Regarding this, I think it has little flaw in design - pulling whole collection with all the data does not scale, which is why I introduced iterative approach.

**Comment by oDinZu** [comment]
> Please feel free to reuse whatever you feel to :)

Awesome and thank  you.

> Regarding this, I think it has little flaw in design - pulling whole collection with all the data does not scale, which is why I introduced iterative approach.

I am unsure what you mean; let me explain a bit more.

 I don't need to use ```?populate=*``` in the code base or in the browser, i simply navigate to that link in browser to see if image json data is loading xor to see new variable names; this allows me then to apply appropriate Jekyll code to iterate the image data; as an example: ```{{ post.attributes.image.data.attributes.url }}```. If that Jekyll code isn't there, the data isn't pulled.

On **build** of Jekyll site, I pull all post data from Strapi server and each post is already iterated while building Jekyll. Then, __site dir is pushed to prod server._ 

It would be great to have cache working for each array i.e. posts, products, etc.. 

1. check if local data exists
2. if true exit
3. if false download data to cache dir

**Comment by bluszcz** [comment]
Hello, I am sorry but now I failed with an understanding :)

What is confusing for me - step in the browser. With approach in PR it is simplified - iteration over collection which user configured, provided complete documents for the user, and user renders/copy only what necessary. Copying locally medias from Strapi server I added since without it - my links with images were pointing to the Strapi server, and I haven't found a way to do it. Writing code was easier.

Actually I got an idea, for another optimisation patch - to specify in the collection config which fields are necessary and just use these fields :)

**Comment by bluszcz** [comment]
Due to massive changes in other PR: https://github.com/strapi/jekyll-strapi/pull/27 and much better code and docs organization in new PR - I am invalidating this one.

**Pull request closed without merging**
